services:
  cyber-guardians-api:
    container_name: cyber-guardians-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/api  
    ports:
      - "8000:8000" 
    env_file:
      - .env
      
